# Generated by Django 2.1.7 on 2019-02-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0057_auto_20190211_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='alternative_specs_submitted',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Alternative specs submitted (if required)'),
        ),
    ]
